name: hillel auto e2e tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened]

env:
  WORK_ENV: DEV
  user: ${{ secrets.USER_EMAIL }}
  password: ${{ secrets.USER_PASSWORD }}
  siteAuthUserName: ${{ secrets.SITE_AUTH_USER }}
  siteAuthPassword: ${{ secrets.SITE_AUTH_PASSWORD }}

jobs:
  cypress_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests
      run: |
        echo "User Email: $user"
        echo "User Password: $password"
        echo "Site Auth User: $siteAuthUserName"
        echo "Site Auth Password: $siteAuthPassword"
        npm run cy:smoke-tests

    - name: Create report
      if: success() || failure()
      run: npm run report:all

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: mochawesome-report/
