name: hillel auto e2e tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened]

env:
  WORK_ENV: DEV
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SITEAUTHUSERNAME: ${{ secrets.SITEAUTHUSERNAME }}
  SITEAUTHPASSWORD: ${{ secrets.SITEAUTHPASSWORD }}

jobs:
  cypress_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests
      run: |
        echo "User Email: $USER_EMAIL"
        echo "User Password: $USER_PASSWORD"
        echo "Site Auth User: $SITE_AUTH_USER"
        echo "Site Auth Password: $SITE_AUTH_PASSWORD"
        npm run cy:smoke-tests

    - name: Create report
      if: success() || failure()
      run: npm run report:all

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: mochawesome-report/
